// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patchgl.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "patchgl.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace patchgl {

namespace {

const ::google::protobuf::Descriptor* BeginPatch_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BeginPatch_reflection_ = NULL;
const ::google::protobuf::Descriptor* BeginPatch_Position_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BeginPatch_Position_reflection_ = NULL;
const ::google::protobuf::Descriptor* BeginPatch_Color_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BeginPatch_Color_reflection_ = NULL;
const ::google::protobuf::Descriptor* BeginPatchResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BeginPatchResponse_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_patchgl_2eproto() {
  protobuf_AddDesc_patchgl_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "patchgl.proto");
  GOOGLE_CHECK(file != NULL);
  BeginPatch_descriptor_ = file->message_type(0);
  static const int BeginPatch_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatch, position_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatch, color_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatch, parent_),
  };
  BeginPatch_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      BeginPatch_descriptor_,
      BeginPatch::default_instance_,
      BeginPatch_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatch, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatch, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(BeginPatch));
  BeginPatch_Position_descriptor_ = BeginPatch_descriptor_->nested_type(0);
  static const int BeginPatch_Position_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatch_Position, left_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatch_Position, right_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatch_Position, top_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatch_Position, bottom_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatch_Position, near_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatch_Position, far_),
  };
  BeginPatch_Position_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      BeginPatch_Position_descriptor_,
      BeginPatch_Position::default_instance_,
      BeginPatch_Position_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatch_Position, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatch_Position, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(BeginPatch_Position));
  BeginPatch_Color_descriptor_ = BeginPatch_descriptor_->nested_type(1);
  static const int BeginPatch_Color_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatch_Color, red_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatch_Color, green_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatch_Color, blue_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatch_Color, alpha_),
  };
  BeginPatch_Color_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      BeginPatch_Color_descriptor_,
      BeginPatch_Color::default_instance_,
      BeginPatch_Color_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatch_Color, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatch_Color, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(BeginPatch_Color));
  BeginPatchResponse_descriptor_ = file->message_type(1);
  static const int BeginPatchResponse_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatchResponse, patch_),
  };
  BeginPatchResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      BeginPatchResponse_descriptor_,
      BeginPatchResponse::default_instance_,
      BeginPatchResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatchResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BeginPatchResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(BeginPatchResponse));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_patchgl_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    BeginPatch_descriptor_, &BeginPatch::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    BeginPatch_Position_descriptor_, &BeginPatch_Position::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    BeginPatch_Color_descriptor_, &BeginPatch_Color::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    BeginPatchResponse_descriptor_, &BeginPatchResponse::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_patchgl_2eproto() {
  delete BeginPatch::default_instance_;
  delete BeginPatch_reflection_;
  delete BeginPatch_Position::default_instance_;
  delete BeginPatch_Position_reflection_;
  delete BeginPatch_Color::default_instance_;
  delete BeginPatch_Color_reflection_;
  delete BeginPatchResponse::default_instance_;
  delete BeginPatchResponse_reflection_;
}

void protobuf_AddDesc_patchgl_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rpatchgl.proto\022\007patchgl\"\245\002\n\nBeginPatch\022"
    ".\n\010position\030\001 \002(\0132\034.patchgl.BeginPatch.P"
    "osition\022(\n\005color\030\002 \002(\0132\031.patchgl.BeginPa"
    "tch.Color\022\021\n\006parent\030\003 \001(\007:\0010\032e\n\010Position"
    "\022\014\n\004left\030\001 \002(\002\022\r\n\005right\030\002 \002(\002\022\013\n\003top\030\003 \002"
    "(\002\022\016\n\006bottom\030\004 \002(\002\022\017\n\004near\030\005 \001(\002:\0011\022\016\n\003f"
    "ar\030\006 \001(\002:\0011\032C\n\005Color\022\013\n\003red\030\001 \002(\002\022\r\n\005gre"
    "en\030\002 \002(\002\022\014\n\004blue\030\003 \002(\002\022\020\n\005alpha\030\004 \001(\002:\0011"
    "\"#\n\022BeginPatchResponse\022\r\n\005patch\030\001 \002(\007", 357);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "patchgl.proto", &protobuf_RegisterTypes);
  BeginPatch::default_instance_ = new BeginPatch();
  BeginPatch_Position::default_instance_ = new BeginPatch_Position();
  BeginPatch_Color::default_instance_ = new BeginPatch_Color();
  BeginPatchResponse::default_instance_ = new BeginPatchResponse();
  BeginPatch::default_instance_->InitAsDefaultInstance();
  BeginPatch_Position::default_instance_->InitAsDefaultInstance();
  BeginPatch_Color::default_instance_->InitAsDefaultInstance();
  BeginPatchResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_patchgl_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_patchgl_2eproto {
  StaticDescriptorInitializer_patchgl_2eproto() {
    protobuf_AddDesc_patchgl_2eproto();
  }
} static_descriptor_initializer_patchgl_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int BeginPatch_Position::kLeftFieldNumber;
const int BeginPatch_Position::kRightFieldNumber;
const int BeginPatch_Position::kTopFieldNumber;
const int BeginPatch_Position::kBottomFieldNumber;
const int BeginPatch_Position::kNearFieldNumber;
const int BeginPatch_Position::kFarFieldNumber;
#endif  // !_MSC_VER

BeginPatch_Position::BeginPatch_Position()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:patchgl.BeginPatch.Position)
}

void BeginPatch_Position::InitAsDefaultInstance() {
}

BeginPatch_Position::BeginPatch_Position(const BeginPatch_Position& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:patchgl.BeginPatch.Position)
}

void BeginPatch_Position::SharedCtor() {
  _cached_size_ = 0;
  left_ = 0;
  right_ = 0;
  top_ = 0;
  bottom_ = 0;
  near_ = 1;
  far_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BeginPatch_Position::~BeginPatch_Position() {
  // @@protoc_insertion_point(destructor:patchgl.BeginPatch.Position)
  SharedDtor();
}

void BeginPatch_Position::SharedDtor() {
  if (this != default_instance_) {
  }
}

void BeginPatch_Position::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BeginPatch_Position::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return BeginPatch_Position_descriptor_;
}

const BeginPatch_Position& BeginPatch_Position::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_patchgl_2eproto();
  return *default_instance_;
}

BeginPatch_Position* BeginPatch_Position::default_instance_ = NULL;

BeginPatch_Position* BeginPatch_Position::New() const {
  return new BeginPatch_Position;
}

void BeginPatch_Position::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<BeginPatch_Position*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 63) {
    ZR_(left_, bottom_);
    near_ = 1;
    far_ = 1;
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool BeginPatch_Position::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:patchgl.BeginPatch.Position)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required float left = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &left_)));
          set_has_left();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_right;
        break;
      }

      // required float right = 2;
      case 2: {
        if (tag == 21) {
         parse_right:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &right_)));
          set_has_right();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_top;
        break;
      }

      // required float top = 3;
      case 3: {
        if (tag == 29) {
         parse_top:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &top_)));
          set_has_top();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(37)) goto parse_bottom;
        break;
      }

      // required float bottom = 4;
      case 4: {
        if (tag == 37) {
         parse_bottom:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &bottom_)));
          set_has_bottom();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(45)) goto parse_near;
        break;
      }

      // optional float near = 5 [default = 1];
      case 5: {
        if (tag == 45) {
         parse_near:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &near_)));
          set_has_near();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(53)) goto parse_far;
        break;
      }

      // optional float far = 6 [default = 1];
      case 6: {
        if (tag == 53) {
         parse_far:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &far_)));
          set_has_far();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:patchgl.BeginPatch.Position)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:patchgl.BeginPatch.Position)
  return false;
#undef DO_
}

void BeginPatch_Position::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:patchgl.BeginPatch.Position)
  // required float left = 1;
  if (has_left()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->left(), output);
  }

  // required float right = 2;
  if (has_right()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->right(), output);
  }

  // required float top = 3;
  if (has_top()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->top(), output);
  }

  // required float bottom = 4;
  if (has_bottom()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->bottom(), output);
  }

  // optional float near = 5 [default = 1];
  if (has_near()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->near(), output);
  }

  // optional float far = 6 [default = 1];
  if (has_far()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->far(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:patchgl.BeginPatch.Position)
}

::google::protobuf::uint8* BeginPatch_Position::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:patchgl.BeginPatch.Position)
  // required float left = 1;
  if (has_left()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->left(), target);
  }

  // required float right = 2;
  if (has_right()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->right(), target);
  }

  // required float top = 3;
  if (has_top()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->top(), target);
  }

  // required float bottom = 4;
  if (has_bottom()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->bottom(), target);
  }

  // optional float near = 5 [default = 1];
  if (has_near()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->near(), target);
  }

  // optional float far = 6 [default = 1];
  if (has_far()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->far(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:patchgl.BeginPatch.Position)
  return target;
}

int BeginPatch_Position::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required float left = 1;
    if (has_left()) {
      total_size += 1 + 4;
    }

    // required float right = 2;
    if (has_right()) {
      total_size += 1 + 4;
    }

    // required float top = 3;
    if (has_top()) {
      total_size += 1 + 4;
    }

    // required float bottom = 4;
    if (has_bottom()) {
      total_size += 1 + 4;
    }

    // optional float near = 5 [default = 1];
    if (has_near()) {
      total_size += 1 + 4;
    }

    // optional float far = 6 [default = 1];
    if (has_far()) {
      total_size += 1 + 4;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BeginPatch_Position::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const BeginPatch_Position* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const BeginPatch_Position*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void BeginPatch_Position::MergeFrom(const BeginPatch_Position& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_left()) {
      set_left(from.left());
    }
    if (from.has_right()) {
      set_right(from.right());
    }
    if (from.has_top()) {
      set_top(from.top());
    }
    if (from.has_bottom()) {
      set_bottom(from.bottom());
    }
    if (from.has_near()) {
      set_near(from.near());
    }
    if (from.has_far()) {
      set_far(from.far());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void BeginPatch_Position::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BeginPatch_Position::CopyFrom(const BeginPatch_Position& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BeginPatch_Position::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void BeginPatch_Position::Swap(BeginPatch_Position* other) {
  if (other != this) {
    std::swap(left_, other->left_);
    std::swap(right_, other->right_);
    std::swap(top_, other->top_);
    std::swap(bottom_, other->bottom_);
    std::swap(near_, other->near_);
    std::swap(far_, other->far_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata BeginPatch_Position::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = BeginPatch_Position_descriptor_;
  metadata.reflection = BeginPatch_Position_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int BeginPatch_Color::kRedFieldNumber;
const int BeginPatch_Color::kGreenFieldNumber;
const int BeginPatch_Color::kBlueFieldNumber;
const int BeginPatch_Color::kAlphaFieldNumber;
#endif  // !_MSC_VER

BeginPatch_Color::BeginPatch_Color()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:patchgl.BeginPatch.Color)
}

void BeginPatch_Color::InitAsDefaultInstance() {
}

BeginPatch_Color::BeginPatch_Color(const BeginPatch_Color& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:patchgl.BeginPatch.Color)
}

void BeginPatch_Color::SharedCtor() {
  _cached_size_ = 0;
  red_ = 0;
  green_ = 0;
  blue_ = 0;
  alpha_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BeginPatch_Color::~BeginPatch_Color() {
  // @@protoc_insertion_point(destructor:patchgl.BeginPatch.Color)
  SharedDtor();
}

void BeginPatch_Color::SharedDtor() {
  if (this != default_instance_) {
  }
}

void BeginPatch_Color::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BeginPatch_Color::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return BeginPatch_Color_descriptor_;
}

const BeginPatch_Color& BeginPatch_Color::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_patchgl_2eproto();
  return *default_instance_;
}

BeginPatch_Color* BeginPatch_Color::default_instance_ = NULL;

BeginPatch_Color* BeginPatch_Color::New() const {
  return new BeginPatch_Color;
}

void BeginPatch_Color::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<BeginPatch_Color*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 15) {
    ZR_(red_, blue_);
    alpha_ = 1;
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool BeginPatch_Color::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:patchgl.BeginPatch.Color)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required float red = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &red_)));
          set_has_red();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_green;
        break;
      }

      // required float green = 2;
      case 2: {
        if (tag == 21) {
         parse_green:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &green_)));
          set_has_green();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_blue;
        break;
      }

      // required float blue = 3;
      case 3: {
        if (tag == 29) {
         parse_blue:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &blue_)));
          set_has_blue();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(37)) goto parse_alpha;
        break;
      }

      // optional float alpha = 4 [default = 1];
      case 4: {
        if (tag == 37) {
         parse_alpha:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &alpha_)));
          set_has_alpha();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:patchgl.BeginPatch.Color)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:patchgl.BeginPatch.Color)
  return false;
#undef DO_
}

void BeginPatch_Color::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:patchgl.BeginPatch.Color)
  // required float red = 1;
  if (has_red()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->red(), output);
  }

  // required float green = 2;
  if (has_green()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->green(), output);
  }

  // required float blue = 3;
  if (has_blue()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->blue(), output);
  }

  // optional float alpha = 4 [default = 1];
  if (has_alpha()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->alpha(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:patchgl.BeginPatch.Color)
}

::google::protobuf::uint8* BeginPatch_Color::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:patchgl.BeginPatch.Color)
  // required float red = 1;
  if (has_red()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->red(), target);
  }

  // required float green = 2;
  if (has_green()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->green(), target);
  }

  // required float blue = 3;
  if (has_blue()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->blue(), target);
  }

  // optional float alpha = 4 [default = 1];
  if (has_alpha()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->alpha(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:patchgl.BeginPatch.Color)
  return target;
}

int BeginPatch_Color::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required float red = 1;
    if (has_red()) {
      total_size += 1 + 4;
    }

    // required float green = 2;
    if (has_green()) {
      total_size += 1 + 4;
    }

    // required float blue = 3;
    if (has_blue()) {
      total_size += 1 + 4;
    }

    // optional float alpha = 4 [default = 1];
    if (has_alpha()) {
      total_size += 1 + 4;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BeginPatch_Color::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const BeginPatch_Color* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const BeginPatch_Color*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void BeginPatch_Color::MergeFrom(const BeginPatch_Color& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_red()) {
      set_red(from.red());
    }
    if (from.has_green()) {
      set_green(from.green());
    }
    if (from.has_blue()) {
      set_blue(from.blue());
    }
    if (from.has_alpha()) {
      set_alpha(from.alpha());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void BeginPatch_Color::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BeginPatch_Color::CopyFrom(const BeginPatch_Color& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BeginPatch_Color::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void BeginPatch_Color::Swap(BeginPatch_Color* other) {
  if (other != this) {
    std::swap(red_, other->red_);
    std::swap(green_, other->green_);
    std::swap(blue_, other->blue_);
    std::swap(alpha_, other->alpha_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata BeginPatch_Color::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = BeginPatch_Color_descriptor_;
  metadata.reflection = BeginPatch_Color_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int BeginPatch::kPositionFieldNumber;
const int BeginPatch::kColorFieldNumber;
const int BeginPatch::kParentFieldNumber;
#endif  // !_MSC_VER

BeginPatch::BeginPatch()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:patchgl.BeginPatch)
}

void BeginPatch::InitAsDefaultInstance() {
  position_ = const_cast< ::patchgl::BeginPatch_Position*>(&::patchgl::BeginPatch_Position::default_instance());
  color_ = const_cast< ::patchgl::BeginPatch_Color*>(&::patchgl::BeginPatch_Color::default_instance());
}

BeginPatch::BeginPatch(const BeginPatch& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:patchgl.BeginPatch)
}

void BeginPatch::SharedCtor() {
  _cached_size_ = 0;
  position_ = NULL;
  color_ = NULL;
  parent_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BeginPatch::~BeginPatch() {
  // @@protoc_insertion_point(destructor:patchgl.BeginPatch)
  SharedDtor();
}

void BeginPatch::SharedDtor() {
  if (this != default_instance_) {
    delete position_;
    delete color_;
  }
}

void BeginPatch::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BeginPatch::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return BeginPatch_descriptor_;
}

const BeginPatch& BeginPatch::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_patchgl_2eproto();
  return *default_instance_;
}

BeginPatch* BeginPatch::default_instance_ = NULL;

BeginPatch* BeginPatch::New() const {
  return new BeginPatch;
}

void BeginPatch::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_position()) {
      if (position_ != NULL) position_->::patchgl::BeginPatch_Position::Clear();
    }
    if (has_color()) {
      if (color_ != NULL) color_->::patchgl::BeginPatch_Color::Clear();
    }
    parent_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool BeginPatch::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:patchgl.BeginPatch)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .patchgl.BeginPatch.Position position = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_position()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_color;
        break;
      }

      // required .patchgl.BeginPatch.Color color = 2;
      case 2: {
        if (tag == 18) {
         parse_color:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_color()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_parent;
        break;
      }

      // optional fixed32 parent = 3 [default = 0];
      case 3: {
        if (tag == 29) {
         parse_parent:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &parent_)));
          set_has_parent();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:patchgl.BeginPatch)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:patchgl.BeginPatch)
  return false;
#undef DO_
}

void BeginPatch::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:patchgl.BeginPatch)
  // required .patchgl.BeginPatch.Position position = 1;
  if (has_position()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->position(), output);
  }

  // required .patchgl.BeginPatch.Color color = 2;
  if (has_color()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->color(), output);
  }

  // optional fixed32 parent = 3 [default = 0];
  if (has_parent()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(3, this->parent(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:patchgl.BeginPatch)
}

::google::protobuf::uint8* BeginPatch::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:patchgl.BeginPatch)
  // required .patchgl.BeginPatch.Position position = 1;
  if (has_position()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->position(), target);
  }

  // required .patchgl.BeginPatch.Color color = 2;
  if (has_color()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->color(), target);
  }

  // optional fixed32 parent = 3 [default = 0];
  if (has_parent()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed32ToArray(3, this->parent(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:patchgl.BeginPatch)
  return target;
}

int BeginPatch::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .patchgl.BeginPatch.Position position = 1;
    if (has_position()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->position());
    }

    // required .patchgl.BeginPatch.Color color = 2;
    if (has_color()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->color());
    }

    // optional fixed32 parent = 3 [default = 0];
    if (has_parent()) {
      total_size += 1 + 4;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BeginPatch::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const BeginPatch* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const BeginPatch*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void BeginPatch::MergeFrom(const BeginPatch& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_position()) {
      mutable_position()->::patchgl::BeginPatch_Position::MergeFrom(from.position());
    }
    if (from.has_color()) {
      mutable_color()->::patchgl::BeginPatch_Color::MergeFrom(from.color());
    }
    if (from.has_parent()) {
      set_parent(from.parent());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void BeginPatch::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BeginPatch::CopyFrom(const BeginPatch& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BeginPatch::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_position()) {
    if (!this->position().IsInitialized()) return false;
  }
  if (has_color()) {
    if (!this->color().IsInitialized()) return false;
  }
  return true;
}

void BeginPatch::Swap(BeginPatch* other) {
  if (other != this) {
    std::swap(position_, other->position_);
    std::swap(color_, other->color_);
    std::swap(parent_, other->parent_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata BeginPatch::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = BeginPatch_descriptor_;
  metadata.reflection = BeginPatch_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int BeginPatchResponse::kPatchFieldNumber;
#endif  // !_MSC_VER

BeginPatchResponse::BeginPatchResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:patchgl.BeginPatchResponse)
}

void BeginPatchResponse::InitAsDefaultInstance() {
}

BeginPatchResponse::BeginPatchResponse(const BeginPatchResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:patchgl.BeginPatchResponse)
}

void BeginPatchResponse::SharedCtor() {
  _cached_size_ = 0;
  patch_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BeginPatchResponse::~BeginPatchResponse() {
  // @@protoc_insertion_point(destructor:patchgl.BeginPatchResponse)
  SharedDtor();
}

void BeginPatchResponse::SharedDtor() {
  if (this != default_instance_) {
  }
}

void BeginPatchResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BeginPatchResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return BeginPatchResponse_descriptor_;
}

const BeginPatchResponse& BeginPatchResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_patchgl_2eproto();
  return *default_instance_;
}

BeginPatchResponse* BeginPatchResponse::default_instance_ = NULL;

BeginPatchResponse* BeginPatchResponse::New() const {
  return new BeginPatchResponse;
}

void BeginPatchResponse::Clear() {
  patch_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool BeginPatchResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:patchgl.BeginPatchResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required fixed32 patch = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &patch_)));
          set_has_patch();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:patchgl.BeginPatchResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:patchgl.BeginPatchResponse)
  return false;
#undef DO_
}

void BeginPatchResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:patchgl.BeginPatchResponse)
  // required fixed32 patch = 1;
  if (has_patch()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(1, this->patch(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:patchgl.BeginPatchResponse)
}

::google::protobuf::uint8* BeginPatchResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:patchgl.BeginPatchResponse)
  // required fixed32 patch = 1;
  if (has_patch()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed32ToArray(1, this->patch(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:patchgl.BeginPatchResponse)
  return target;
}

int BeginPatchResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required fixed32 patch = 1;
    if (has_patch()) {
      total_size += 1 + 4;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BeginPatchResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const BeginPatchResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const BeginPatchResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void BeginPatchResponse::MergeFrom(const BeginPatchResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_patch()) {
      set_patch(from.patch());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void BeginPatchResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BeginPatchResponse::CopyFrom(const BeginPatchResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BeginPatchResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void BeginPatchResponse::Swap(BeginPatchResponse* other) {
  if (other != this) {
    std::swap(patch_, other->patch_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata BeginPatchResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = BeginPatchResponse_descriptor_;
  metadata.reflection = BeginPatchResponse_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace patchgl

// @@protoc_insertion_point(global_scope)
