[package]
name = "patchgl"
version = "0.1.0"
authors = ["Jeffrey Yu <wehjin@gmail.com>"]

[dependencies]
glium = "*"
xml-rs = "0.3"
cage = { git = "https://github.com/wehjin/rust-cage" }

[lib]
name = "libpatchgl"
path = "src/lib.rs"

[[bin]]
name = "patchgl"
path = "src/main.rs"
